# netlify.toml
[build]
  publish = "."
  
[[redirects]]
  from = "/api/*"
  to = "https://lectorhuellas.onrender.com"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"